[package]
authors = ["K900 <me@0upti.me>", "Jake McGinty <jake@tonari.no>"]
categories = ["os::unix-apis"]
description = "High level bindings to the WireGuard embeddable C library"
edition = "2021"
license = "LGPL-2.1-or-later"
name = "wireguard-control"
readme = "README.md"
repository = "https://github.com/tonarino/innernet"
version = "1.5.3"

[dependencies]
base64 = "0.13"
hex = "0.4"
libc = "0.2"
log = "0.4"
rand_core = "0.6"
curve25519-dalek = "4.0.0-pre.1"

[target.'cfg(target_os = "linux")'.dependencies]
netlink-request = { path = "../netlink-request" }
netlink-sys = "0.8"
netlink-packet-core = "0.4"
netlink-packet-generic = "0.3"
netlink-packet-route = "0.10"
netlink-packet-wireguard = { git = "https://github.com/little-dude/netlink", rev = "b2bdd6295209c84ef95f85f66c03b55234d77ad6" }
